monitor=,preferred,auto,auto

###################
### MY PROGRAMS ###
###################

#conf location
$CONFIG = ~/.config/hypr

source = $CONFIG/variables.conf

#################
### AUTOSTART ###
#################

source = $CONFIG/exec.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#############
###VISUALS###
#############
source = $CONFIG/visual.conf
source = $CONFIG/animations.conf
source = $CONFIG/misc.conf  

#############
### INPUT ###
#############
source = $CONFIG/input.conf

###################
### KEYBINDINGS ###
###################
source = $CONFIG/bind.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = $CONFIG/windowrules.conf

