monitor=,preferred,auto,auto


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty -e fish
$fileManager = $terminal -ic yazi
$menu = rofi -show drun -run-command "sh -c 'uwsm app -- {cmd}||{cmd}'" -theme-str'*{font:"Cantarell 10";}' -theme-str 'window {border: 3px;border-radius:0px;} element {border-radius:10px;}' -theme-str 'configuration {icon-theme:"Tela-circle-grey";}' -theme ~/.config/rofi/style_8.rasi 
$browser = zen-browser 
$cliphist = cliphist list | rofi -dmenu -multi-select -i -display-colums 2 -theme-str 'window { border: 3px; border-radius:0px;}' -theme-str 'element {border-radius: 5px;}' -theme-str '* {font: "JetBrainsMono Nerd Font 10";}' -theme ~/.config/rofi/clipboard.rasinc | cliphist decode | wl-copy
$nvim = $terminal -ic nvim
$btop = $terminal -ic btop
$screenshot = grim -g "$(slurp)" - | satty -f - --copy-command wl-copy
$CONFIG = ~/.config/hypr

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = nm-applet 
exec-once = waybar & awww-daemon 
exec-once = wl-paste --watch cliphist store
exec-once = awww img ~/.config/hypr/walpapa.jpg
#############################
### ENVIRONMENT VARIABLES ###
#############################


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#window decoration
source = $CONFIG/visual.conf


# animations on default
source = $CONFIG/animations.conf
  

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


#############
### INPUT ###
#############
source = $CONFIG/input.conf



###################
### KEYBINDINGS ###
###################
source = $CONFIG/bind.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

layerrule = blur on, ignore_alpha 0, match:namespace rofi
windowrule = match:class rofi, opacity 0.2
windowrule = match:class kitty, opacity 0.8

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
