
$terminal = kitty -e fish
$fileManager = $terminal -ic yazi
$menu = rofi -show drun -run-command "sh -c 'uwsm app -- {cmd}||{cmd}'" -theme-str'*{font:"Cantarell 10";}' -theme-str 'window {border: 3px;border-radius:0px;} element {border-radius:10px;}' -theme-str 'configuration {icon-theme:"Tela-circle-grey";}' -theme ~/.config/rofi/style_8.rasi 
$browser = zen-browser 
$cliphist = cliphist list | rofi -dmenu -multi-select -i -display-colums 2 -theme-str 'window { border: 3px; border-radius:0px;}' -theme-str 'element {border-radius: 5px;}' -theme-str '* {font: "JetBrainsMono Nerd Font 10";}' -theme ~/.config/rofi/clipboard.rasinc | cliphist decode | wl-copy
$nvim = $terminal -ic nvim
$btop = $terminal -ic btop
$screenshot = grim -g "$(slurp)" - | satty -f - --copy-command wl-copy

